# Generated by Django 4.1.7 on 2023-04-06 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
