# Generated by Django 4.1.7 on 2023-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subcategory_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pic', models.ImageField(upload_to='images')),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
