# Generated by Django 4.1.7 on 2023-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Header',
            field=models.CharField(default='hi', max_length=300),
        ),
        migrations.AddField(
            model_name='slider',
            name='SubHeader',
            field=models.CharField(default='hi', max_length=300),
        ),
    ]
