# Generated by Django 4.1.7 on 2023-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_slider_header_slider_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
