# Generated by Django 4.1.7 on 2023-04-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_alter_subcategory_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='info',
        ),
    ]
