# Generated by Django 4.1.7 on 2023-04-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('Message', models.CharField(max_length=1000)),
                ('Subject', models.CharField(max_length=300)),
            ],
        ),
    ]
