# Generated by Django 4.1.7 on 2023-04-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Time',
        ),
    ]
