# Generated by Django 4.1.7 on 2023-04-16 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
