# Generated by Django 4.1.7 on 2023-04-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contact_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
