# Generated by Django 4.1.7 on 2023-04-16 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_contact_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pic', models.ImageField(upload_to='images')),
                ('slug', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(default=500)),
                ('category', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('subcategory', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
            ],
        ),
    ]
